#!/bin/bash

set -xeuo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ln -i -s "$DIR/vimrc" ~/.vimrc

for source in autoload ftplugin; do 
  fn=`basename "$source"`
  ln -Fi -h -s "$DIR/$source" ~/.vim/"$fn"
done
